import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./_global-components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "RoleMate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen bg-slate-950`}
      >
        {/* Header */}
        <header>
        <Header />

        </header>

        {/* Main Content */}
         <main
          className="h-[calc(100vh-104px)] "
        >
          {children}
        </main>
      </body>
    </html>
  );
}